export const FETCH_HOME_REQUEST = 'FETCH_HOME_REQUEST';
export const FETCH_HOME_SUCCESS = 'FETCH_HOME_SUCCESS';
export const FETCH_HOME_ERROR = 'FETCH_HOME_ERROR';

export const FETCH_DOMAIN_REQUEST = 'FETCH_DOMAIN_REQUEST';
export const FETCH_DOMAIN_SUCCESS = 'FETCH_DOMAIN_SUCCESS';
export const FETCH_DOMAIN_ERROR = 'FETCH_DOMAIN_ERROR';

export const FETCH_CURRENT_ARTICLE_REQUEST = 'FETCH_CURRENT_ARTICLE_REQUEST';
export const FETCH_CURRENT_ARTICLE_SUCCESS = 'FETCH_CURRENT_ARTICLE_SUCCESS';
export const FETCH_CURRENT_ARTICLE_ERROR = 'FETCH_CURRENT_ARTICLE_ERROR';

// TODO: refactor to just FETCH_TRENDS
export const FETCH_PROPER_TRENDS_REQUEST = 'FETCH_PROPER_TRENDS_REQUEST';
export const FETCH_PROPER_TRENDS_SUCCESS = 'FETCH_PROPER_TRENDS_SUCCESS';
export const FETCH_PROPER_TRENDS_ERROR = 'FETCH_PROPER_TRENDS_ERROR';

